src/smartcoding_shop/cart/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='cart_remove'),
    path('checkout/', views.proceed_to_checkout, name='proceed-to-checkout'),
    path('confirmed/', TemplateView.as_view(template_name='cart/confirmed.html'), name='confirmed'),
    path('failed/', TemplateView.as_view(template_name='cart/failed.html'), name='failed'),

]

src/smartcoding_shop/smartcoding_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory.views import index, about
from marketing.views import team

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('cart/', include('cart.urls')),
    path('product/', include('inventory.urls')),
    path('about/', about, name='about'),
    path('team/', team, name='team'),
    path('stripe/', include('djstripe.urls', namespace='djstripe')),
]

src/smartcoding_shop/cart/models.py
from django.db import models

# Create your models here.

src/smartcoding_shop/checkout/models.py
from django.db import models

# Create your models here.

src/smartcoding_shop/cart/forms.py
from django import forms


class AddProductToCartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=[(i, str(i)) for i in range(1, 10)])
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/smartcoding_shop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from inventory.models import Product
import math
from payments.models import Payment
from .cart import Cart
from .forms import AddProductToCartForm
import stripe

stripe.api_key = "sk_test_RR2Rq4iUe11rYdOTt6ka06Up"


@require_POST
def add_to_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductToCartForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add(product=product, quantity=cleaned_data['quantity'], update_quantity=cleaned_data['quantity'])
    return redirect('cart:cart_detail')


def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = AddProductToCartForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})


# TODO -> more work has to be done "after holiday" to properly extra addresses of the customer
def proceed_to_checkout(request):
    cart = Cart(request)
    total = math.ceil(cart.get_total_price()*100)

    if request.method == 'POST':
        stripeToken = request.POST['stripeToken']
        charge = stripe.Charge.create(
            amount=total,
            currency='eur',
            description='Amount charge, TODO -> replace with email of customer',
            source=stripeToken
        )
        payment = Payment(stripe_id=charge.id, amount=cart.get_total_price(), paid=charge.paid)
        payment.save()
        # empty cart
        cart.clear()
        return redirect('cart:confirmed')
    return render(request, 'cart/checkout.html', {'cart': cart, 'total': total})

src/smartcoding_shop/checkout/views.py
from django.shortcuts import render

# Create your views here.

src/smartcoding_shop/cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load l10n %}


{% block content %}
    <div class="row">
        <div class="col-md-6 cardly">
            <div class="thecard">
                <div class="top-card">
                    <div class="circle"></div>
                    <div class="card-title">The Card</div>
                </div>
                <div class="card-info">
                    <div class="card-number">1234 5678 9012 3456</div>
                    <div class="exp-date">01 / 2018</div>
                    <div class="card-holder">John Doe</div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h2>Total amount due: € {{ total|localize }}</h2>
            <div class="form">

                <form action="" method="post" id="payment-form">
                    {% csrf_token %}
                    <div class="form-row">
                        <label for="card-element">
                            Credit or debit card
                        </label>
                        <div id="card-element">
                            <!-- A Stripe Element will be inserted here. -->
                        </div>

                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>

                    <button>Submit Payment</button>
                </form>
                {#TODO -> redesign stripe auto forms to look like the one commented out#}
                {#                <form class="payment-form">#}
                {#                    {% csrf_token %}#}
                {#                    <div class="form-group">#}
                {#                        <label for="cardnumber">Card Number</label>#}
                {#                        <input#}
                {#                                type="text"#}
                {#                                id="cardnumber"#}
                {#                                placeholder="1234 5678 9012 3456"#}
                {#                                class="form-control"#}
                {#                                name="cardnumber"#}
                {#                                style="background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAfBJREFUWAntVk1OwkAUZkoDKza4Utm61iP0AqyIDXahN2BjwiHYGU+gizap4QDuegWN7lyCbMSlCQjU7yO0TOlAi6GwgJc0fT/fzPfmzet0crmD7HsFBAvQbrcrw+Gw5fu+AfOYvgylJ4TwCoVCs1ardYTruqfj8fgV5OUMSVVT93VdP9dAzpVvm5wJHZFbg2LQ2pEYOlZ/oiDvwNcsFoseY4PBwMCrhaeCJyKWZU37KOJcYdi27QdhcuuBIb073BvTNL8ln4NeeR6NRi/wxZKQcGurQs5oNhqLshzVTMBewW/LMU3TTNlO0ieTiStjYhUIyi6DAp0xbEdgTt+LE0aCKQw24U4llsCs4ZRJrYopB6RwqnpA1YQ5NGFZ1YQ41Z5S8IQQdP5laEBRJcD4Vj5DEsW2gE6s6g3d/YP/g+BDnT7GNi2qCjTwGd6riBzHaaCEd3Js01vwCPIbmWBRx1nwAN/1ov+/drgFWIlfKpVukyYihtgkXNp4mABK+1GtVr+SBhJDbBIubVw+Cd/TDgKO2DPiN3YUo6y/nDCNEIsqTKH1en2tcwA9FKEItyDi3aIh8Gl1sRrVnSDzNFDJT1bAy5xpOYGn5fP5JuL95ZjMIn1ya7j5dPGfv0A5eAnpZUY3n5jXcoec5J67D9q+VuAPM47D3XaSeL4AAAAASUVORK5CYII='); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;"#}
                {#                        />#}
                {#                    </div>#}
                {#                    <div class="form-group">#}
                {#                        <label for="cardholder">Card Holder</label>#}
                {#                        <input#}
                {#                                type="text"#}
                {#                                id="cardholder"#}
                {#                                class="form-control"#}
                {#                                placeholder="John Doe"#}
                {#                                name="name"#}
                {#                        />#}
                {#                    </div>#}
                {#                    <div class="form-group">#}
                {#                        <label for="exp">Expiration Date</label>#}
                {#                        <div class="date">#}
                {#                            <select name="month" id="month" class="form-control">#}
                {#                                <option value="january">January</option>#}
                {#                                <option value="february">February</option>#}
                {#                                <option value="march">March</option>#}
                {#                                <option value="april">April</option>#}
                {#                                <option value="may">May</option>#}
                {#                                <option value="june">June</option>#}
                {#                                <option value="july">July</option>#}
                {#                                <option value="august">August</option>#}
                {#                                <option value="september">September</option>#}
                {#                                <option value="october">October</option>#}
                {#                                <option value="november">November</option>#}
                {#                                <option value="december">December</option>#}
                {#                            </select>#}
                {#                            <select name="year" class="form-control">#}
                {#                                <option value="2018">2018</option>#}
                {#                                <option value="2019">2019</option>#}
                {#                                <option value="2020">2020</option>#}
                {#                                <option value="2021">2021</option>#}
                {#                                <option value="2022">2022</option>#}
                {#                                <option value="2023">2023</option>#}
                {#                                <option value="2024">2024</option>#}
                {#                            </select>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                    <div class="small form-group">#}
                {#                        <div class="cvc">#}
                {#                            <label for="cvc">CVC</label>#}
                {#                            <input#}
                {#                                    type="text"#}
                {#                                    id="cvc"#}
                {#                                    maxlength="3"#}
                {#                                    size="4"#}
                {#                                    name="cvc"#}
                {#                                    placeholder="123"#}
                {#                                    class="form-control"#}
                {#                            />#}
                {#                        </div>#}
                {#                        <p>#}
                {#                            Three or four digits, usually found on the back of the card#}
                {#                        </p>#}
                {#                    </div>#}
                {#                    <button id='pay' class="btn btn-primary btn-block btn-lg">Proceed</button>#}
                {#                </form>#}
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(function () {
            $('.breadcrumb div').on('click', function (e) {
                e.preventDefault();
                $(this).siblings().removeClass('active');
                $(this).addClass('active confirmed');
            });

            $('#shipping').on('click', function (e) {
                e.preventDefault();
                $('.shipping').show();
                $('.payment').hide();
                $('.confirmOrder').hide();
            });

            $('#paymentMethod').on('click', function (e) {
                e.preventDefault();
                $('.payment').show();
                $('.shipping').hide();
                $('.confirmOrder').hide();
            });
            /*
                        var stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx');
                        $('.payment-form').on('submit', function (e) {
                            e.preventDefault();
                            var $form = $(this);
                            $form.find('#pay').prop('disabled', true); // prevent button from being active to avoid multiple clicks
                            stripe.createToken($form, function (status, response) {
                                if (response.error) {
                                    // todo handle errors
                                } else {
                                    var token = response.id;
                                    $form.append($('<input type="hidden" name="stripeToken"/>').val(token));
                                    $form.get(0).submit();
                                }
                            });

                        })
                        */


            // Create a Stripe client.
            var stripe = Stripe('pk_test_9T4lNGz4vNn9B5VBsvAFMFWH');

            // Create an instance of Elements.
            var elements = stripe.elements();

            // Custom styling can be passed to options when creating an Element.
            var style = {
                base: {
                    color: '#32325d',
                    lineHeight: '18px',
                    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                    fontSmoothing: 'antialiased',
                    fontSize: '16px',
                    '::placeholder': {
                        color: '#aab7c4'
                    }
                },
                invalid: {
                    color: '#fa755a',
                    iconColor: '#fa755a'
                }
            };

            // Create an instance of the card Element.
            var card = elements.create('card', {style: style});

            // Add an instance of the card Element into the `card-element` <div>.
            card.mount('#card-element');

            // Handle real-time validation errors from the card Element.
            card.addEventListener('change', function (event) {
                var displayError = document.getElementById('card-errors');
                if (event.error) {
                    displayError.textContent = event.error.message;
                } else {
                    displayError.textContent = '';
                }
            });

            // Handle form submission.
            var form = document.getElementById('payment-form');
            form.addEventListener('submit', function (event) {
                event.preventDefault();

                stripe.createToken(card).then(function (result) {
                    if (result.error) {
                        // Inform the user if there was an error.
                        var errorElement = document.getElementById('card-errors');
                        errorElement.textContent = result.error.message;
                    } else {
                        // Send the token to your server.
                        stripeTokenHandler(result.token);
                    }
                });
            });

            // Submit the form with the token ID.
            function stripeTokenHandler(token) {
                // Insert the token ID into the form so it gets submitted to the server
                var form = document.getElementById('payment-form');
                var hiddenInput = document.createElement('input');
                hiddenInput.setAttribute('type', 'hidden');
                hiddenInput.setAttribute('name', 'stripeToken');
                hiddenInput.setAttribute('value', token.id);
                form.appendChild(hiddenInput);

                // Submit the form
                form.submit();
            }
        });
    </script>

{% endblock %}

src/smartcoding_shop/cart/templates/cart/confirmed.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="col-md-12">
        Successfully charged
    </div>
{% endblock %}

src/smartcoding_shop/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}

{% block content %}
    <div class="col-md-12">
        <h2>Your shopping cart
            <span class="badge badge-secondary pull-right">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        My order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #fff">
                        {{ total_items }} item {{ total_items|pluralize }}, € {{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Your cart is empty
                    {% endif %}
                {% endwith %}
        </span>
        </h2>
        <table class="table table-striped table-hover">
            <thead style="background-color: #5AC8FA">
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get__absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                     alt="..." style="height: 130px; width: auto">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="Update" class="btn btn-info">
                            </form>
                        </td>
                        <td>
                            <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                        </td>
                        <td>€ {{ item.price }}</td>
                        <td>€ {{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr style="background-color: #5AC8FA">
                <td><b>Total</b></td>
                <td colspan="4"></td>
                <td colspan="num"><b>€ {{ cart.get_total_price }}</b></td>
            </tr>
            </tbody>
        </table>

        <a href="{% url 'cart:proceed-to-checkout' %}" class="btn btn-primary">Proceed to checkout <i class="fas fa-credit-card"></i></a>
    </div>
{% endblock %}

src/smartcoding_shop/cart/templates/cart/failed.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="col-md-12">
        Failed to charge card
    </div>
{% endblock %}