src/smartcoding_shop/cart/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='cart_remove'),
    path('checkout/', views.proceed_to_checkout, name='proceed-to-checkout'),
    path('confirmed/', TemplateView.as_view(template_name='cart/confirmed.html'), name='confirmed'),
    path('failed/', TemplateView.as_view(template_name='cart/failed.html'), name='failed'),

]

src/smartcoding_shop/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('', views.product_list, name='catalog'),
    path('add-product/', views.add_product, name='add_product'),
    path('<int:product_id>/', views.detail, name='product_detail')
]

src/smartcoding_shop/smartcoding_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory.views import index, about
from marketing.views import team

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('cart/', include('cart.urls')),
    path('product/', include('inventory.urls')),
    path('about/', about, name='about'),
    path('team/', team, name='team'),
    path('stripe/', include('djstripe.urls', namespace='djstripe')),
]

src/smartcoding_shop/inventory/models.py
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=255, blank=False, db_index=True)
    image = CloudinaryField('image') # Other options can be done through the ImageField
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # improve how the model presents itself as a string
    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def __unicode__(self):
        try:
            public_id = self.image.public_id
        except AttributeError:
            public_id = ''
        return 'Product <%s:%s>' % (self.name, public_id)

    def get_absolute_url(self):
        # we'll create a SEO friendly URL
        return reverse('inventory:product_detail', args=[self.id, self.slug])

src/smartcoding_shop/inventory/forms.py
from django.forms import ModelForm
from cloudinary.forms import CloudinaryJsFileField, CloudinaryUnsignedJsFileField

from cloudinary.compat import to_bytes
import cloudinary, hashlib
from .models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class ProductDirectForm(ProductForm):
    image = CloudinaryJsFileField()

class ProductUnsignedDirectForm(ProductForm):
    upload_preset_name = 'sample_' + hashlib.sha1(to_bytes(cloudinary.config().api_key + cloudinary.config().api_secret)).hexdigest()[0:10]
    image = CloudinaryUnsignedJsFileField(upload_preset_name)

src/smartcoding_shop/inventory/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from cloudinary import api
from cloudinary.forms import cl_init_js_callbacks
import six
from .forms import ProductForm, ProductDirectForm, ProductUnsignedDirectForm
from .models import Product
from cart.forms import AddProductToCartForm


def about(request):
    return render(request, 'inventory/about.html')


def index(request):
    return render(request, 'inventory/index.html')


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart_product_form = AddProductToCartForm()
    return render(request, 'inventory/detail.html', dict(product=product, cart_product_form=cart_product_form))


def add_product(request):
    unsigned = request.GET.get('unsigned') == 'true'

    if (unsigned):
        try:
            api.upload_preset(ProductUnsignedDirectForm.upload_preset_name)
        except api.NotFound:
            api.create_upload_preset(name=ProductUnsignedDirectForm.upload_preset_name, unsigned=True,
                                     folder='preset_folder')

    direct_form = ProductUnsignedDirectForm() if unsigned else ProductDirectForm()
    context = dict(backend_form=ProductForm(), direct_form=direct_form, unsigned=unsigned)
    # when using direct upload - the following is necessary to update the form's callback url
    cl_init_js_callbacks(context['direct_form'], request)

    if request.method == 'POST':
        # when using backend upload
        form = ProductForm(request.POST, request.FILES)
        context['posted'] = form.instance
        if form.is_valid():
            # upload image and create model instance
            form.save()
            return HttpResponseRedirect(reverse('inventory:product_detail', args=(form.instance.id,)))

    return render(request, 'inventory/add_product.html', context)


def filter_nones(d):
    return dict((k, v) for k, v in six.iteritems(d) if v is not None)


def product_list(request):
    defaults = dict(format='jpg', height=150, width=150)
    defaults['class'] = 'thumbnail inline'

    # The different transformations to present
    samples = [
        dict(crop="fill", radius=10),
        dict(crop="scale"),
        dict(crop="fit", format="png"),
        dict(crop="thumb", gravity="face"),
        dict(format="png", angle=20, height=None, width=None, transformation=[
            dict(crop="fill", gravity="north", width=150, height=150, effect="sepia"),
        ]),
    ]
    samples = [filter_nones(dict(defaults, **sample)) for sample in samples]
    return render(request, 'inventory/products.html', dict(products=Product.objects.all(), samples=samples))

src/smartcoding_shop/inventory/templates/inventory/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-lg-12">
        <h2 class="page-header">This is an About page</h2>
    </div>
{%  endblock %}

src/smartcoding_shop/inventory/templates/inventory/add_product.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}

{% block content %}
    <div class="row data-entry">
        <div class="col-lg-12">
            <h1>Adding new product</h1>
            <div class="alert alert-danger alert-dismissable fade show" role='alert'>
                This should be done by an admin
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action="{% url 'inventory:add_product'%}" method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <table border='1' class='table'>
                {{ backend_form.as_table }}
                </table>
                <br/>
                <!-- <div class="form-group">
                    <label for="name">Name of Product</label>
                    <input name='name' type="text" class='form-control' placeholder="Enter name of product"> 
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <input name='description' type="text" class='form-control' placeholder="Enter description of product"> 
                </div> -->

                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>  
    {% if posted %}  
    <div class="row">
        <div class="col-lg-12">
            {% if posted.errors %}
                Errors: {{ posted.errors }}
            {% else %}

            {% endif %}
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    <!-- 
        an example where versions of jQuery in a plugin work for some and doesn't for others, 
        we override the settings here 
    -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    {% cloudinary_includes %}
    {% cloudinary_js_config %}
    <script>
        $(function(){
            $('button.close').click(function(evt){
                evt.preventDefault();
                $('div.alert-danger').fadeOut();
            });
        });
    </script>
{% endblock %}
    

src/smartcoding_shop/inventory/templates/inventory/detail.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}

{% block content %}
    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventory:catalog' %}">Catalog</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
            </ol>
        </nav>
    </div>
    <div class="col-md-8">
        <img src="{{ product.image.url }}" alt="" class="rounded float-left">
    </div>
    <div class="col-md-4 product">
        <h2 class="text-center">{{ product.name }}</h2>
        <div class="price">
            €{{ product.price }}
        </div>
        <div class="description">
            {{ product.description|safe|linebreaksbr }}
        </div>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{ cart_product_form }}
            <button class="btn btn-primary btn-block"><i class="fas fa-cart-plus"></i>Add to cart</button>
        </form>

    </div>
{% endblock %}

src/smartcoding_shop/inventory/templates/inventory/index.html
<!-- first tag here -->
{% extends "base.html" %}
{% load cloudinary %}
<!-- second tag to register static files -->
{% load static %}

<!-- start pluging your content in here -->
{% block content %}

<h2 class="break-corner">New Arrivals</h2>

<div class="row">
  <div class="col-md-3">
    <div class="product-top">
      <img src="{% static '/images/3.jpg' %}" alt="lady boots" />
      <div class="overlay">
        <button type="button" class="btn btn-secondary" title="Quick shop">
          <i class="fas fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to wishlist">
          <i class="fas fa-heart"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Cart">
          <i class="fas fa-shopping-cart"></i>
        </button>
      </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fas fa-star"></i> <i class="fas fa-star"></i>
      <i class="fas fa-star-half"></i> <i class="far fa-star"></i>
      <i class="far fa-star"></i>
      <h3>Rock 'em boots</h3>
      <h5>€ 250</h5>
    </div>
  </div>

  <div class="col-md-3">
    <div class="product-top">
      <img src="{% static '/images/5.jpg' %}" alt="lady boots" />
      <div class="overlay">
        <button type="button" class="btn btn-secondary" title="Quick shop">
          <i class="fas fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to wishlist">
          <i class="fas fa-heart"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Cart">
          <i class="fas fa-shopping-cart"></i>
        </button>
      </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fas fa-star"></i> <i class="fas fa-star"></i>
      <i class="fas fa-star"></i> <i class="far fa-star"></i>
      <i class="far fa-star"></i>
      <h3>Classic Man boots</h3>
      <h5>€ 150</h5>
    </div>
  </div>
  <div class="col-md-3">
    <div class="product-top">
      <img src="{% static '/images/6.jpg' %}" alt="mocasins" />
      <div class="overlay">
        <button type="button" class="btn btn-secondary" title="Quick shop">
          <i class="fas fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to wishlist">
          <i class="fas fa-heart"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Cart">
          <i class="fas fa-shopping-cart"></i>
        </button>
      </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fas fa-star"></i> <i class="fas fa-star"></i>
      <i class="fas fa-star"></i> <i class="far fa-star"></i>
      <i class="far fa-star"></i>
      <h3>Rock a moc!</h3>
      <h5>€ 250</h5>
    </div>
  </div>
  <div class="col-md-3">
    <div class="product-top">
      <img src="{% static '/images/7.jpg' %}" alt="lady boots" />
      <div class="overlay">
        <button type="button" class="btn btn-secondary" title="Quick shop">
          <i class="fas fa-eye"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to wishlist">
          <i class="fas fa-heart"></i>
        </button>
        <button type="button" class="btn btn-secondary" title="Add to Cart">
          <i class="fas fa-shopping-cart"></i>
        </button>
      </div>
    </div>
    <div class="product-bottom text-center">
      <i class="fas fa-star"></i> <i class="fas fa-star"></i>
      <i class="far fa-star"></i> <i class="far fa-star"></i>
      <i class="far fa-star"></i>
      <h3>Gentle city look</h3>
      <h5>€ 110</h5>
    </div>
  </div>
</div>
<br />
<h1 class="text-center">&#9924; Black Friday Deals &#9924;</h1>
<div class="row">    
    <div id="snowflakeContainer">
        <p class="snowflake">*</p>
    </div>  
</div>
<br />
<div class="row">
  <div class="col-md-5">
    <div id="carouselExampleControls" class="carousel slide">
      <div class="xcarousel-inner">
        <div class="carousel-item active">
          <img
            class="d-block w-100"
            src="{%static '/images/1.jpg'%}"
            alt="First slide"
          />
        </div>
        <div class="carousel-item">
          <img
            class="d-block w-100"
            src="{%static '/images/2.jpg'%}"
            alt="Second slide"
          />
        </div>
        <div class="carousel-item">
          <img
            class="d-block w-100"
            src="{%static '/images/3.jpg'%}"
            alt="Third slide"
          />
        </div>
      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleControls"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleControls"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

  <div class="col-md-7">
    <p class="new-arrival text-center">NEW</p>
    <h2>Amazing Shoes</h2>
    <p>Product Code: SMARTCODING</p>
    <i class="fas fa-star"></i> <i class="fas fa-star"></i>
    <i class="fas fa-star"></i> <i class="fas fa-star"></i>
    <i class="fas fa-star-half"></i>
    <p class="price">EUR 30</p>
    <p><b>Availability:</b>LIMITED</p>
    <label for="">Quantity</label>
    <p><b>Brand:</b> NIKE</p>
    <input type="text" value="1" class="qty" />
    <button class="btn btn-default cart">Add to cart</button>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-12">
      
    <h3 class="headline">FRI FRAKT OCH FRIA RETURER FÖR ALLA</h3>
    <p class="text">
        {% cloudinary "officialchucknorrispage" ICON_EFFECTS %}</br>
      Erbjudandet aktiveras i kassan. Fri frakt gäller fram till 2018-12-24 och
      fria returer till 2019-01-31.
    </p>
  </div>
</div>
{% endblock %}
{% block scripts %}
{{block.super}}
<script src="{% static '/js/fallingsnow_v6.js' %}"></script>
{% endblock %}

src/smartcoding_shop/inventory/templates/inventory/products.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}

{% block content %}
{% for product in products %}
    <h2>{{product.name}}</h2>
    <img src="{{product.image.url}}"> 
    <hr><br/>
{% endfor %}
{% endblock %}