src/smartcoding_shop/cart/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='cart_remove'),
    path('checkout/', views.proceed_to_checkout, name='proceed-to-checkout'),
    path('confirmed/', TemplateView.as_view(template_name='cart/confirmed.html'), name='confirmed'),
    path('failed/', TemplateView.as_view(template_name='cart/failed.html'), name='failed'),

]

src/smartcoding_shop/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('', views.product_list, name='catalog'),
    path('add-product/', views.add_product, name='add_product'),
    path('<int:product_id>/', views.detail, name='product_detail')
]

src/smartcoding_shop/smartcoding_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory.views import index, about
from marketing.views import team

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('cart/', include('cart.urls')),
    path('product/', include('inventory.urls')),
    path('about/', about, name='about'),
    path('team/', team, name='team'),
    path('stripe/', include('djstripe.urls', namespace='djstripe')),
]

src/smartcoding_shop/templates/base.html
{% load static %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <meta name="Description" content="Smartcoding Practice eShop">
    <meta name="theme-color">
    <title>Shop</title>
    <script src="https://js.stripe.com/v3/"></script>
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    />
    <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
    />
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>
    {% block styles %}
    {% endblock %}
</head>
<body>
<div class="container">
    <ul class="navigation">
        <li class='branding'><a href="{% url 'index' %}"><img src="{% static '/images/smart-logo.png' %}" alt=""/> eShop</a>
        </li>
        <li><a href="#">Dam</a></li>
        <li><a href="#">Herr</a></li>
        <li><a href="#">Barn</a></li>
        <li><a href="{% url 'inventory:catalog' %}">Catalog</a></li>
        <li><a href="{% url 'team' %}">Team</a></li>
        <li><a href="{% url 'cart:cart_detail' %}" style="width: 100px;">
            <i class="fas fa-shopping-cart"></i>
            {% if cart|length > 0 %}
                <div class="badge badge-success">{{ cart|length }}</div>
            {% endif %}
        </a></li>
    </ul>

    <div class="row">
        {% block content %} {% endblock %}
    </div>
</div>
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <span class="text-muted">Smartcoding eShop&copy; 2018</span>
            </div>
        </div>

    </div>
</footer>
<!-- You can add more custom javascript code -->
{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
{% endblock %}
</body>
</html>